# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: go build -v -o demo-app ./...

    - name: Run Tests
      run: go test -v ./...

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0
      with:
        sonar-project-key: DonnerMarcel_CICD
        sonar-organization: donnermarcel
        sonar-token: ${{ secrets.SONAR_TOKEN }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-app
        path: ./demo-app
