# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: go build -v -o demo-app ./...

    - name: Run Tests
      run: go test -v ./...
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-app
        path: ./demo-app

  sonarCloud:
      needs: build
      name: SonarCloud Code Analysis
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
  
      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        with:
          args: >
            -Dsonar.organization=donnermarcel
            -Dsonar.projectKey=DonnerMarcel_CICD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
